name: CI

on: [push]
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      - name: Run bias_review.py
        run: python bias_review.py

      - name: Run safety_review.py
        run: python safety_review.py

      - name: Run demo.py
        run: python demo.py

      - name: Run gemini.py
        run: python gemini.py

